databases:
  - name: toy_app
    ipAllowList: []
    # databaseName: toy_app_k0ti
    # user: toy_app_k0ti_user

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: 56e7b3127953bd0603c0e851bbc7688d
        sync: false
      - key: postgres://toy_app_k0ti_user:VjopLdvJ1WTuWvTbV1SdsP3b2VMPJpFr@dpg-cedckasgqg45ht9a00s0-a/toy_app_k0ti
        fromDatabase:
          name: toy_app
          property: connectionString
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
